### ISSUE TITLE
Can this method be applied to coaxial large-angle diffraction calculations? And does this method require zero-padding to avoid circular convolution errors?

### ISSUE THREAD

**Issue by lalalashini** [whywww/ASASM#2]

**Comment by whywww** [comment]
Do you mean point sources from different depths in the same direction by "coaxial"? If yes, then LS-ASM supports it.

**Comment by whywww** [comment]
For your second question, zero-padding is not needed as our method has already considered the circular convolution problems.

**Comment by lalalashini** [comment]
Thank you for your response. Regarding my first question, I would like to clarify that this method can indeed be used for calculating diffraction in on-axis non-paraxial scenarios, such as when a plane wave propagates along the z-axis and undergoes large-angle diffraction after modulation of the phase.

**Comment by lalalashini** [comment]
"zero-padding is not needed as our method has already considered the circular convolution problems." Where should this section be placed in the article?

**Comment by whywww** [comment]
> 

I see. In that case, you may still follow the two major equations in the paper (Eqs. 4 and 6) for the calculation. For the input field, compute the center of its angular spectrum and compensate it; for the frequency domain, take the observation window wherever you wish, and compute the shift amount following Supplementary (Eqs. S20-S23).

**Comment by whywww** [comment]
> "zero-padding is not needed as our method has already considered the circular convolution problems." Where should this section be placed in the article?

The aim of zero-padding is to enlarge the frequency sampling region to cover the full effective spectrum when you are using FFT, as it does not allow you to alter the frequency region. But we use MTP which allows you to choose the destination frequency coordinates. And our sampling calculations ensure there is little aliasing in that region.

**Comment by lalalashini** [comment]
Thank you for your response. I would like to ask if using your method to calculate diffraction field in on-axis non-paraxial scenarios would be faster compared to the conventional ASM method? Because in Figure 4 of the article, the LS-ASM time is equivalent to the shift-ASM at 0 degrees.

**Comment by whywww** [comment]
Yes, it would. For an on-axis non-paraxial case, the angular spectrum is still shifted from the origin, so you need to compensate for the linear phase even if the input field is on-axis (like the case of a cubic plate). Then you would get a speed gain using our method.

**Comment by lalalashini** [comment]
Thank you for your patient response and your work.
