### ISSUE TITLE
Defocused PSF for a F/4 lens

### ISSUE THREAD

**Issue by niarmi** [whywww/ASASM#3]
Hi, thank you for sharing this fantastic code! I've been playing around the lens parameters in main.py. I noticed that the original code used an F/16 lens. However, when applied an F/4 lens, I observed a defocused PSF. Have you encountered a similar issue? Is paraxial approximation applied in the code? Or do you know how to fix this issue? Thanks a lot!

![image](https://github.com/whywww/ASASM/assets/118702136/bc2d4d22-e915-4f55-9b87-040c995ab005)

**Comment by whywww** [comment]
Hi niarmi, the method can be used for any set of camera parameters as long as computing memory allows. Paraxial is not assumed and we follow strict ASM principles. For debugging, I would suggest you always check the angular spectrum to see if there exist any spectrum overlays/cropped frequencies etc. But from your plot, I cannot decide if this is a defocus pattern or simply diffraction rings. You could perhaps move the sensor plane axially to see if the PSF grows/shrinks...

**Comment by niarmi** [comment]
Thanks for your input! I enlarged the z0 value and fixed this.
